### ISSUE TITLE
Make the bot to react at specific key words

### ISSUE THREAD

**Issue by ImSpiker** [Rocci1212/RoboticNightmare#21]
Like when someone asks for iso it should remove the post and send via dm the Pal Iso.
The keywords i have in mind are 
'download the game' 'share the wbfs' 'share the iso'
'Get iso'
'send Wbfs file'
'Where to dl the game'
'I need to get pal'
'someone give me the game'
'how to get the game'
'someone send iso'

In addition i would suggest that the bot give the competitive rules of both games when someone use the key word 'competitive rules'
And when someone ask how to setup wimmfi, the bot automatically give #strikers101 as a response

**Comment by odreikosen** [comment]
Hmm finding a the perfect set of phrases that find the middle ground between useful and spam would be tough, although those seem like a good start. Too avoid the bot spamming a channel during a convo that happens to include keyword I would assume there would potentially be a timeout on this action? I’m thinking of a potentially general response for anything we have a command for and point them to the list of bot commands.

**Comment by odreikosen** [comment]
All In all it seems like it would help out moderators

**Comment by Rocci1212** [comment]
closing this out for now, maybe it's something we can come back to later
